import blogImage1 from "@/assets/img/blog/blog__1.png";
import blogImage2 from "@/assets/img/blog/blog__2.png";
import blogImage3 from "@/assets/img/blog/blog__3.png";
import blogImage4 from "@/assets/img/blog/blog__4.png";
import blogImage5 from "@/assets/img/blog/blog__5.png";
import blogImage6 from "@/assets/img/blog/blog__6.png";
import blogImage7 from "@/assets/img/blog/blog__7.png";
import blogImage8 from "@/assets/img/blog/blog__8.png";
import blogImage9 from "@/assets/img/blog/blog__9.png";
const getAllBlogs = () => {
  const blogs = [
    {
      id: 1,
      title:
        "",
      img: blogImage1,
      desc: "Empower mammas by creating sustainable markets through recycling, producing eco-friendly goods, and fostering financial independence and creative thinking through training and mentorship.",
      tag: "Management",
      category: "Supply Chain Optimization",
      day: "",
      publishDate: "10 Dec, 2024",
      date: "Mission",
      duration: "1500",
    },
    {
      id: 2,
      title: "",
      img: blogImage2,
      desc: "Empowering 1,050 struggling mammas annually by training them as artisans in the production of handcrafted paper goods and as marketing ambassadors for proactive recycling.",
      tag: "Start-up",
      category: "Supply Chain Optimization",
      day: "",
      publishDate: "11 Dec, 2024",
      date: "Community Empowerment",
      duration: "1800",
    },
    {
      id: 3,
      title: "",
      img: blogImage3,
      desc: "Promoting recycling and upcycling to transform waste into sustainable products, protecting the environment and supporting biodiversity.",
      tag: "Start-up",
      category: "Supply Chain Optimization",
      day: "",
      publishDate: "12 Dec, 2024",
      date: "Sustainable Environment",
      duration: "2100",
    },
    {
      id: 4,
      title:
        "5 Strategies to Transform Your Business with Effective Consulting",
      img: blogImage4,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Management",
      category: "Strategic Planning",
      day: 19,
      publishDate: "14 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
    },
    {
      id: 5,
      title: "Why Every Startup Needs a Business Consultant",
      img: blogImage5,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Consulting",
      category: "Market Entry Strategy",
      day: 12,
      publishDate: "16 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
    },
    {
      id: 6,
      title: "How Marketing Consultants Can Double Your Revenue in 6 Months",
      img: blogImage6,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Start-up",
      category: "Supply Chain Optimization",
      day: 21,
      publishDate: "16 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
    },
    {
      id: 7,
      title:
        "The Ultimate Guide to Choosing the Right Marketing Consultant for Your Brand",
      img: blogImage7,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Management",
      category: "Strategic Planning",
      day: 19,
      publishDate: "17 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
    },
    {
      id: 8,
      title:
        "Corporate Strategy: How to Align Business Goals with Organizational Success",
      img: blogImage8,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Start-up",
      category: "Supply Chain Optimization",
      day: 12,
      publishDate: "18 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
    },
    {
      id: 9,
      title:
        "The Role of Corporate Culture in Business Growth: A Consultant's Perspective",
      img: blogImage9,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Consulting",
      category: "Market Entry Strategy",
      day: 21,
      publishDate: "27 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
    },
    {
      id: 10,
      title: "Why Digital Agencies Are the Backbone of Modern Business Growth",
      img: blogImage5,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Management",
      category: "Strategic Planning",
      day: 19,
      publishDate: "14 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
    },
    {
      id: 11,
      title: "Top 5 Digital Marketing Trends for Agencies in 2024",
      img: blogImage6,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Consulting",
      category: "Market Entry Strategy",
      day: 12,
      publishDate: "16 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
    },
    {
      id: 12,
      title:
        "How Finance Consulting Can Help Your Business Survive Economic Downturns",
      img: blogImage7,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Marketing",
      category: "Financial Restructuring",
      day: 21,
      publishDate: "16 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
    },
    {
      id: 13,
      title: "The Importance of Financial Planning in Scaling Your Business",
      img: blogImage9,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Consulting",
      category: "Market Entry Strategy",
      day: 19,
      publishDate: "17 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
    },
    {
      id: 14,
      title: "Human Resource Consulting: How to Build a High-Performing Team",
      img: blogImage8,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Management",
      category: "Strategic Planning",
      day: 12,
      publishDate: "18 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
    },
    {
      id: 15,
      title: "The Future of HR: Trends Every Business Needs to Know in 2024",
      img: blogImage4,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Operation",
      category: "Business Process",
      day: 21,
      publishDate: "27 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
    },
    {
      id: 16,
      title: "How Creative Agencies Are Revolutionizing Brand Identity",
      img: blogImage6,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Consulting",
      category: "Market Entry Strategy",
      day: 19,
      publishDate: "14 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
    },
    {
      id: 17,
      title: "The Power of Storytelling in Creative Agency Campaigns",
      img: blogImage8,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "HR Management",
      category: "Cost Reduction Analysis",
      day: 12,
      publishDate: "16 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
    },
    {
      id: 18,
      title: "eCommerce Growth Hacks: Insights from Industry Experts",
      img: blogImage5,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Operation",
      category: "Business Process",
      day: 21,
      publishDate: "16 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
    },
    {
      id: 19,
      title: "How to Boost Your eCommerce Sales with Strategic Consulting",
      img: blogImage7,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Marketing",
      category: "Financial Restructuring",
      day: 19,
      publishDate: "17 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
    },
    {
      id: 20,
      title: "Building a Personal Brand: Tips for an Impressive Portfolio",
      img: blogImage9,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Marketing",
      category: "Financial Restructuring",
      day: 12,
      publishDate: "18 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
    },
    {
      id: 21,
      title: "Why a Strong Personal Portfolio is Crucial for Business Success",
      img: blogImage4,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Start-up",
      category: "Supply Chain Optimization",
      day: 21,
      publishDate: "27 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
    },
  ];
  return blogs;
};

export default getAllBlogs;
